title: 'Appeals Board Land Acquisition'
description: Description
url: 'https://ab.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
useful_links_url: 'https://staging-isomer-mlaw.netlify.com/useful-links/'
'useful_links_url external': false
resources_name: resource-room
favicon: /images/favicon-minlaw.ico
google-analytics: UA-10405444-18
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://staging.d22l77zpqkkmie.amplifyapp.com/
prod: https://master.d22l77zpqkkmie.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: '#a40935'
  secondary-color: '#a40935'
  media-colors:
    - title: media-color-one
      color: '#696969'
    - title: media-color-two
      color: '#800000'
    - title: media-color-three
      color: '#A0522D'
    - title: media-color-four
      color: '#866633'
    - title: media-color-five
      color: '#505050'
