title: Appeals Board Land Acquisition 
title-abbreviated: Title
description: >- # this means to ignore newlines until "baseurl:"
  Description
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: true

# Feedback Form URL
feedback_form_url: "https://www.mlaw.gov.sg/eservices/enquiry/"

# FAQ URL
faq_url: "https://va.ecitizen.gov.sg/cfp/customerPages/mlaw/explorefaq.aspx"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

useful_links_url: "https://staging-isomer-mlaw.netlify.com/useful-links/"
useful_links_url external: false

collections:
  about-us:
    output: true
  legislation:
    output: true
  services:
    output: true
  hearings-and-decisions:
    output: true
  forms:
    output: true
  faqs:
    output: true
  glossary:
    output: true
resources_name: resource-room
